### PR TITLE
Cleaned writing to file.

### PR DESCRIPTION
**Pull request by ghost**
You were getting a table and cleaning it with string.strip I changed it to display only one row of table

### CODE REVIEW

**Comment by thegeniesghost** [comment]
I accept your help.

**Comment by ghost** [comment]
sorry i only check the FOR loop

**Comment by thegeniesghost** [comment]
Its ok the project you wanted me to work on, i can't as i know nothing
about algorithms/encryption. Other projects feel free to contact me about
all the best,

thegeniesghost

**Comment by ghost** [comment]
I didin't use itertools earlier and i didn't test all code but only loop. I want to use your code in shacrack project. At your project txt file will be very big. in my calculation with 8 character pass the txt file will be more than 1PB

**Comment by thegeniesghost** [comment]
You have my permission to use the code as you wish.

**Pull request merged**
